//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// CharaTool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CharaToolTYPE               130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_Ctl_Pane                    310
#define IDD_Ctl_Form                    311
#define IDD_Effect_Form1                312
#define IDD_Effect_Form2                313
#define ID_NEW_OBJ                      1000
#define IDC_OBJ_LIST                    1001
#define ID_NAME_MODY                    1002
#define ID_NEW_TEXTURE                  1006
#define IDC_OBJ_NAME_EDIT               1007
#define IDC_TEXTURE_LIST                1008
#define IDC_FADEIN_TIME                 1010
#define IDC_SELECT_TEXTURE              1010
#define IDC_FADEOUT_TIME                1011
#define IDC_LIFE_TIME                   1012
#define IDC_BLOOP                       1013
#define IDC_SAVE                        1013
#define IDC_LOAD                        1014
#define IDC_POWER_X                     1014
#define IDC_POWER_Y                     1015
#define IDC_BACK_COLOR                  1015
#define IDC_POWER_Z                     1016
#define IDC_ADD_TIME                    1017
#define IDC_ANIM_TIME                   1018
#define IDC_ANIM_CUT_X                  1019
#define IDC_FORM2_UPDATE                1020
#define IDC_ANIM_CUT_Y                  1021
#define IDC_MOVE_X_EXP1                 1022
#define IDC_BBILL                       1023
#define IDC_MOVE_X_EXP2                 1024
#define IDC_FILTER_COLOR                1025
#define IDC_RPOWER_MIN_X                1026
#define IDC_RPOWER_MIN_Y                1027
#define IDC_RPOWER_MIN_Z                1028
#define IDC_MOVE_X_A                    1029
#define IDC_MOVE_Y_A                    1030
#define IDC_FADEOUT_TIME2               1031
#define IDC_MOVE_Y_EXP1                 1032
#define IDC_MOVE_X_B                    1033
#define IDC_MOVE_X_C                    1034
#define IDC_SCALE_X                     1035
#define IDC_SCALE_Y                     1036
#define IDC_SCALE_Z                     1037
#define IDC_ROTATION_X                  1038
#define IDC_ROTATION_Y                  1039
#define IDC_ROTATION_Z                  1040
#define IDC_TRANS_X                     1041
#define IDC_TRANS_Y                     1042
#define IDC_TRANS_Z                     1043
#define IDC_MOVE_X_D                    1044
#define IDC_TARGET_X                    1045
#define IDC_TARGET_Y                    1046
#define IDC_TARGET_Z                    1047
#define IDC_MOVE_X_E                    1048
#define IDC_SPEED                       1049
#define IDC_MOVE_Y_B                    1050
#define IDC_MOVE_Y_C                    1051
#define IDC_MOVE_Y_D                    1052
#define IDC_MOVE_Y_E                    1053
#define IDC_MOVE_Y_EXP2                 1054
#define IDC_MOVE_Z_A                    1055
#define IDC_MOVE_Z_B                    1056
#define IDC_MOVE_Z_C                    1057
#define IDC_MOVE_Z_D                    1058
#define IDC_MOVE_Z_E                    1059
#define IDC_MOVE_Z_EXP1                 1060
#define IDC_MOVE_Z_EXP2                 1061
#define IDC_ON                          1062
#define IDC_OFF                         1063
#define IDC_START_TIME                  1064
#define IDC_MOVE_R_A                    1065
#define IDC_MOVE_R_B                    1066
#define IDC_MOVE_R_C                    1067
#define IDC_MOVE_R_D                    1068
#define IDC_MOVE_R_E                    1069
#define IDC_MOVE_R_EXP1                 1070
#define IDC_MOVE_R_EXP2                 1071
#define IDC_END_TIME                    1072
#define IDC_RPOWER_MAX_X                1073
#define IDC_EFFECT_TIME                 1074
#define IDC_RPOWER_MAX_Y                1075
#define IDC_RPOWER_MAX_Z                1076
#define IDC_SCALE_X2                    1080
#define IDC_SCALE_Y2                    1081
#define IDC_SCALE_Z2                    1082
#define IDC_ROTATION_X2                 1083
#define IDC_ROTATION_Y2                 1084
#define IDC_ROTATION_Z2                 1085
#define IDC_TRANS_X2                    1086
#define IDC_TRANS_Y2                    1087
#define IDC_TRANS_Z2                    1088
#define IDC_RANDOM_POS_MIN_X            1089
#define IDC_RANDOM_POS_MIN_Y            1090
#define IDC_RANDOM_POS_MIN_Z            1091
#define IDC_RANDOM_POS_MAX_X            1092
#define IDC_RANDOM_POS_MAX_Y            1093
#define IDC_RANDOM_POS_MAX_Z            1094
#define IDC_ALPHA                       1095

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        315
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
